all: hello

.PHONY: hello
hello:
	python3.9 hello.py

.PHONY: func
func:
	python3.9 func.py

.PHONY: rbac
rbac:
	python3.9 rbac.py

.PHONY: access
access:
	python3.9 access.py

.PHONY: map
map:
	python3.9 map.py

