name: Predicate test workflow
on: [push]
steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version: '3.9.5'
    cache: 'pip' # caching pip dependencies
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        working-directory: python
        run: 'pip install'
      - name: Run tests
        working-directory: python
        run: 'make test'
