name: Predicate test workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./predicate
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.7"
      - name: Install dependencies
        run: |
          sudo apt install gnome-keyring
          pip install poetry
          poetry install
      - name: Run tests
        run: poetry run make test
      - name: Run linter
        run: poetry run make lint-check
